# Numpy 심화

In [1]:
import numpy as np

## 기본연산


In [11]:
x = np.array([[20,30,40],
              [5,6,7],
              [8,9,10]])
y = np.array([[10,20,30],
             [10,11,12],
             [15,18,21]])

* 덧셈과 add

덧셈(+)

In [12]:
x+y

array([[30, 50, 70],
       [15, 17, 19],
       [23, 27, 31]])

add함수를 이용한 덧셈

In [13]:
a = np.add(x,y)
a


array([[30, 50, 70],
       [15, 17, 19],
       [23, 27, 31]])

* 뻴샘과 subtract

In [14]:
x-y

array([[ 10,  10,  10],
       [ -5,  -5,  -5],
       [ -7,  -9, -11]])

In [17]:
b = np.subtract(x,y)
b

array([[ 10,  10,  10],
       [ -5,  -5,  -5],
       [ -7,  -9, -11]])

* 곱셈과 multiyply

In [18]:
x*y

array([[ 200,  600, 1200],
       [  50,   66,   84],
       [ 120,  162,  210]])

In [20]:
c = np.multiply(x,y)
c

array([[ 200,  600, 1200],
       [  50,   66,   84],
       [ 120,  162,  210]])

* 나눗셈과 divide

In [21]:
x/y

array([[2.        , 1.5       , 1.33333333],
       [0.5       , 0.54545455, 0.58333333],
       [0.53333333, 0.5       , 0.47619048]])

In [23]:
d = np.divide(x,y)
d

array([[2.        , 1.5       , 1.33333333],
       [0.5       , 0.54545455, 0.58333333],
       [0.53333333, 0.5       , 0.47619048]])

* 나머지와 remainder = mod

In [24]:
x%y

array([[ 0, 10, 10],
       [ 5,  6,  7],
       [ 8,  9, 10]], dtype=int32)

In [29]:
e = np.remainder(x,y)
e

array([[ 0, 10, 10],
       [ 5,  6,  7],
       [ 8,  9, 10]], dtype=int32)

In [30]:
f = np.mod(x,y)
f

array([[ 0, 10, 10],
       [ 5,  6,  7],
       [ 8,  9, 10]], dtype=int32)

* Broadcasting

영어사전에서 보면  broadcast란 단어는 무언가를 '흩뿌리고 퍼뜨리고 전파'할 때 사용하는 것이라고 한다.    
그래서  부족한 행과 열을 같은 성분으로 채워서 계산하는 방법을 브로드캐스팅(broadcasting)이라고 한다. 

In [34]:
v1 = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
v2 = np.array([1])
v3 = np.array([3,4,5,6])
v4 = np.array([2,2,2,2]).reshape(4,1)

브로드캐스팅이 가능한 경우

1. 멤버가 하나인 배열은 어떤 배열에나 브로드캐스팅이 가능

In [35]:
v1+v2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

2. 하나의 배열의 차원이 1인 경우

In [37]:
v1+v3

array([[ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])

3.  차원의 짝이 맞을 때

In [38]:
v1+v4

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

# 선형대수(벡터/행렬연산)함수

* Norm

벡터의 크기(magnitude) 또는 길이(length)를 측정하는 방법  
* +,- 가 합쳐질 때 모델의 정답과 예측값에 오차 발생가능성이 높다(음수 양수가 번갈아가면서 나오기 떄문)   
* 음수값들을 제거하기 위한 작업 두가지 방법이 있다 
L1_norm, L2_norm
* 컴퓨터가 학습을 잘했는지 안했는지 확인하기 위함도 있다.

L1_norm 

In [40]:
u = np.array([3,-4])
np.abs(u).sum()

7

L2_norm

In [41]:
u = np.array([3.-4])
np.linalg.norm(u)

1.0

* 벡터/행렬의 덧셈과 뺄셈

In [43]:
x = np.array([1,3,5,7,9])
y = np.array([2,4,6,8,10])
x+y

array([ 3,  7, 11, 15, 19])

In [45]:
y-x

array([1, 1, 1, 1, 1])

* 벡터연산(내적)

내적: 벡터를 마치 수 처럼 곱하는 개념이다.  
벡터와 벡터를 연산해서 스칼라의 값을 구하는 개념

1차원 벡터의 내적

In [75]:
a = np.array([1,3,5])
b = np.array([2,4,8])
np.dot(a,b)

54

(1*2)+(3*4)+(5*8)= 54

In [76]:
a.dot(b.T)

54

In [77]:
a@b

54

In [78]:
b.dot(a.T)

54

2차원 벡터의 내적

In [54]:
a = ([[2,4],[3,5]])
b = ([[7,9],[1,8]])
np.dot(a,b)

array([[18, 50],
       [26, 67]])

* 역행렬

In [58]:
np.random.seed(0)

In [65]:
x = np.random.randint(1,4,size=(3,3))

In [66]:
x

array([[2, 2, 2],
       [2, 1, 2],
       [1, 1, 2]])

In [67]:
x1 = np.linalg.inv(x)
x1

array([[ 0. ,  1. , -1. ],
       [ 1. , -1. , -0. ],
       [-0.5,  0. ,  1. ]])

In [68]:
np.dot(x,x1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 난수(랜덤넘버)

rand

random.rand()함수는 주어진 형태의 난수 어레이를 생성한다.

In [92]:
a = np.random.rand(5)
print(a)

b = np.random.rand(2,3)
print(b)

[0.41139672 0.13997259 0.03322239 0.98257496 0.37329075]
[[0.42007537 0.05058812 0.36549611]
 [0.01662797 0.23074234 0.7649117 ]]


randint

random.randint() 함수는 [최소값, 최대값)의 범위에서 임의의 정수를 만듭니다.

In [82]:
a = np.random. randint(2, size=5)
a

array([0, 1, 1, 0, 0])

randn

random.radn()함수는 표준정규분포로부터 샘플링된 난수를 반환한다.

In [87]:
a = np.random.randn(5)
print(a)
b = np.random.randn(2,3)
print(b)
sigma, mu = 1.5, 2.0
c = sigma * np.random.randn(5) + mu
c

[-0.99838235 -0.3676376   1.73719932  0.59361275 -0.54236358]
[[-1.71967238 -0.57890879  1.42694855]
 [ 0.27699691  0.78966713  0.32207411]]


array([3.05058857, 2.58307495, 1.93810421, 2.44382648, 1.36208002])

standard_normal

표준정규분포로부터 샘플링된 난수를 반환한다.  
randn() 함수와 비슷하지만 튜플을 인자로 받는다는 점에서 차이가 있다.

In [88]:
d = np.random.standard_normal(3)
print(d)

e = np.random.standard_normal(2,)
print(e)

[ 1.72763912 -0.86835257 -0.82097758]
[-1.09974201  0.08672983]


normal

In [89]:
a = np.random.normal(0,1,2)
print(a)

b = np.random.normal(1.5, 1.5, 4)
print(b)

c = np.random.normal(3.0, 2.0, (2, 3))
print(c)

[0.45628701 0.4310333 ]
[ 4.6088603   0.69332232 -0.56764514  0.76139362]
[[7.65547622 6.60880793 2.50115735]
 [1.35827234 0.01332008 4.04835189]]


random_sample

random.random_sample() 함수는 [0.0,1.0)범위에서 샘플링된 임의의 실수를 반환합니다.

In [90]:
a = np.random.random_sample()
print(a)

b = np.random.random_sample((5,2))
print(b)

c = 5 * np.random.random_sample((3, 2)) - 3
print(c)

0.10286335869343821
[[0.09237389 0.35404666]
 [0.55181626 0.03362509]
 [0.96896177 0.32099724]
 [0.22126269 0.1412639 ]
 [0.09725993 0.98404224]]
[[-1.69829536 -0.31488739]
 [-0.76036914 -2.50215455]
 [-1.23844169 -0.65375413]]


random.choice()함수는 주어진 1차원 어레이로부터 임의의 샘플을 생성합니다.

In [91]:
a = np.random.choice(5,3)
print(a)

b = np.random.choice(10, (2,3))
print(b)

[4 0 2]
[[3 9 7]
 [5 3 4]]


# 상수

inf

In [81]:
np.inf

inf

nan

In [80]:
np.nan #숫자로 표현이 안된다.

nan

newaxis

차원 추가

In [94]:
x = np.arange(5)
print(x.shape)
x

(5,)


array([0, 1, 2, 3, 4])

In [95]:
x[:, np.newaxis].shape

(5, 1)

In [97]:
x[np.newaxis, :].shape

(1, 5)

In [102]:
x_na = x[:, np.newaxis]
print(x_na.shape)
x_na

(5, 1)


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [101]:
x_na = x[np.newaxis, :]
print(x_na.shape)
x_na

(1, 5)


array([[0, 1, 2, 3, 4]])

In [104]:
x_na_na =x[:, np.newaxis, np.newaxis]
print(x_na_na.shape)
x_na_na

(5, 1, 1)


array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]]])

In [105]:
x_na_na =x[np.newaxis,:,np.newaxis]
print(x_na_na.shape)
x_na_na

(1, 5, 1)


array([[[0],
        [1],
        [2],
        [3],
        [4]]])

In [106]:
x_na_na =x[np.newaxis, np.newaxis, :]
print(x_na_na.shape)
x_na_na

(1, 1, 5)


array([[[0, 1, 2, 3, 4]]])