# Numpy

In [3]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\USER\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-23.1.0               |   py39haa95532_0         946 KB
    ruamel.yaml-0.17.21        |   py39h2bbff1b_0         174 KB
    ruamel.yaml.clib-0.2.6     |   py39h2bbff1b_1         101 KB
    ------------------------------------------------------------
                                           Total:         1.2 MB

The following NEW packages will be INSTALLED:

  ruamel.yaml        pkgs/main/win-64::ruamel.yaml-0.17.21-py39h2bbff1b_0 None
  ruamel.yaml.clib   pkgs/main/win-64::ruamel.yaml.clib-0.2.6-py39h2bbff1b_1 None

The following packages will be UPDATED:

  conda                               22.9.0-py39haa95532_0 --> 23.1.0-py39haa95532_0 None




ruamel.yaml.clib-0.2 | 101 KB    |  

### * Numpy 배우는 이유: 파이썬으로 진행되는 모든 데이터분석과 인공지능 학습에 있어서 가장 필수적으로이해해야 되는 도구입니다.  

### * numpy는 Numerical Python 의 약자로 선형대수의 계산식을 파이썬으로 구현할 수 있도록 도와주는 라이브러리입니다.

Numpy 가져오는 방법

In [9]:
import numpy as np

# 벡터, 행렬

* 벡터(vector)  
    *1차원 데이터(1차원 배열)  
    *스칼라가 연속적으로 여러개 모여 있는것  
        *스칼라:단순하게 측정된 하나의 값

* 행렬(matrix)
    * 2차원 데이터(2차원 배열)
    * 1차원 데이터가 여러개 모여있는 것

## N차원 배열만들기

In [29]:
lst1 = [12,13,14] # 백터
lst1

[12, 13, 14]

In [36]:
lst2 = [
 [
 [12,13,14],
    [12,13,14],
    [12,13,14]
],
    [
 [12,13,14],
    [12,13,14],
    [12,13,14]
],
    [
 [12,13,14],
    [12,13,14],
    [12,13,14]
]
]

In [35]:
ar = np.array(lst2)
ar

array([[[12, 13, 14],
        [12, 13, 14],
        [12, 13, 14]],

       [[12, 13, 14],
        [12, 13, 14],
        [12, 13, 14]],

       [[12, 13, 14],
        [12, 13, 14],
        [12, 13, 14]]])

In [37]:
# 3, 3, 3
ar.shape

(3, 3, 3)

In [44]:
ar.size #데이터 수

27

In [43]:
ar.ndim #배열의 열수

3

In [42]:
ar.shape #배열의 차원

(3, 3, 3)

In [41]:
ar.shape[0] #배열의 열수

3

In [40]:
ar.shape[1] #배열의 행수

3

In [39]:
ar[1] #배열의 원소 접근

array([[12, 13, 14],
       [12, 13, 14],
       [12, 13, 14]])

위의 함수들을 쓰는 것은 데이터를 알맞게 읽고 내가 원하는 방향으로 변환하기 위해 쓴다.

# 특수한 배열의 생성

1씩 증가하는 1차원 배열

In [47]:
arr = np.arange(5) # [0,1,2,3,4] 
arr

array([0, 1, 2, 3, 4])

In [48]:
rg = np.random.default_rng(1)# create instance of default random number generator

In [58]:
np.floor(10* rg.random((2,2)))

array([[8., 5.],
       [5., 7.]])

In [59]:
np.zeros((5,3)) # 영행렬 생성

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.ones((2,3)) # 유닛행렬 생성

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.full((2,3), 5) # 모든 원소가 5인 2x3행렬

array([[5, 5, 5],
       [5, 5, 5]])

In [62]:
np.eye(2) # 단위행렬

array([[1., 0.],
       [0., 1.]])

# 배열 결합

In [66]:
arr1 = np.array([[1, 5],
               [2, 6]])
arr2 = np.array([[3, 7],
               [4, 8]])

In [67]:
np.vstack((arr1, arr2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [68]:
np.hstack((arr1, arr2))

array([[1, 5, 3, 7],
       [2, 6, 4, 8]])

# 배열의 차원 변환

In [69]:
dim = np.arange(20)
dim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
dim.base

In [72]:
dim.shape

(20,)

차원 추가

In [73]:
dim[:, np.newaxis].shape

(20, 1)

In [77]:
np.expand_dims(dim, axis=1).shape

(20, 1)

In [82]:
dim.resize((10,2)) # 10x2행렬

dim

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [86]:
dim.ravel() # returns the array, flattened #일자로 나열

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
dim.T # returns the array, transposed #행 열 바뀜

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [91]:
# If a dimension is given as -1 in a reshaping operation, 
# the other dimensions are automatically calculated:
dim.reshape(4, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [97]:
dim = dim.reshape(2,10)
dim

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [98]:
dim.base

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [99]:
dim.view()

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [100]:
dim.shape

(2, 10)

# 데이터 타입

※ 문자 1개로 데이터 유형을 표시함.

※ 대소문자 구별.

 
i - integer (정수)

b - boolean (참거짓)

u - unsigned integer (부호없는 정수)

f - float (소수)

c - complex (복소수)

m - timedelta (타임델타)

M - datetime (날짜시간)

O - object (객체)

S - string (문자열)

U - unicode string (유니코드 문자열)

V - void (다른 유형에 대한 고정된 메모리 덩어리) 

In [102]:
arr = np.arange(20)
type(arr) # arr의 자료형 확인 #ndarray와 array는 같은표현

numpy.ndarray

In [103]:
arr.dtype # arr의 데이터 자료형 확인

dtype('int32')

In [104]:
arr = arr.astype(np.float32) # 데이터 타입 변환
arr.dtype

dtype('float32')

In [105]:
arr = np.int8(arr) # 데이터 타입 변환
arr.dtype 

dtype('int8')

In [106]:
arr = np.array([1,2,3],dtype = np.int32) # 4바이트 크기의 정수
arr.dtype, arr

(dtype('int32'), array([1, 2, 3]))

In [107]:
arr = np.array([1,2,3],dtype=np.uint8) # 1바이트 크기의 부호 없는 정수(0~255)
arr.dtype, arr

(dtype('uint8'), array([1, 2, 3], dtype=uint8))

In [108]:
arr = np.array([1,2,3],dtype=np.float64) # 8바이트 크기의 실수
arr.dtype, arr

(dtype('float64'), array([1., 2., 3.]))

In [109]:
arr = np.array([1,0,1],dtype=np.bool_)
arr.dtype, arr

(dtype('bool'), array([ True, False,  True]))

# 오버플로 오류 
# NumPy 숫자 유형의 고정 크기 는 값이 데이터 유형에서 사용 가능한 것보다 더 많은 메모리를 필요로 할 때 오버플 로 오류를 일으킬 수 있습니다 . 예를 들어 64비트 정수에 대해 올바르게 numpy.power평가 하지만 32비트 정수에 대해 1874919424(잘못됨)를 제공합니다.

In [110]:
np.power(100, 8, dtype=np.int64) # correct

10000000000000000

In [111]:
np.power(100, 8, dtype=np.int32) # incorrect

1874919424

If 64-bit integers are still too small the result may be cast to a floating point number. Floating point numbers offer a larger, but inexact, range of possible values.

In [113]:
np.power(100, 100, dtype=np.float64) # correct

1e+200

In [114]:
np.power(100, 100, dtype=np.int64) # incorrect

0

# 슬라이싱/인덱싱
## * 슬라이싱: 무언가를 잘라 낸다는 뜻으로 연속적인 객체에 부여된 번호를 이용해 연속된 객체의 일부를 추출하는 작업
## * 인덱싱: 무언가를 가리킨다는 뜻으로 연속적인 객체에 부여된 번호를 의미한다.