# Numpy

Numpy란 무엇인가?

Numpy는 C언어로 구현된 파이썬 라이브러리로써, 고성능의 수치계산을 위해 제작되었습니다. Numerical Python의 줄임말이기도 한 Numpy는 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공합니다.

또한 이는 데이터분석을 할 때 사용되는 라이브러리인 pandas와 matplotlib의 기반으로 사용되기도 합니다

Numpy 설치법

conda install numpy 또는 pip install numpy

* Numpy를 가져오는 방법

In [1]:
import numpy as np # 넘파이를 쓸 때 관레적으로 np를 쓴다.

# 백터와 행렬

 * 백터는 숫자를 원소로 가지는 리스트(list) 또는 배열(array)입니다. np.array()는 행 백터로 나오게 됩니다.   백터는 공간에서 한 점을 나타냅니다. 1차원 공간에서는 백터는 수직선상에 놓인 숫자로 표현하게 됩니다. 2차원 공간에서의 백터는 x축과 y축으로 이뤄진 좌표평면의 한 점을 나타내는 것입니다. 백터는 원점으로부터 상대적 위치를 표현합니다.

* 벡터는 스칼라의 모임입니다

* 스칼라는 단순하게 측정한 하나의 값이다.

* 행렬은 벡터를 원소로 가지는 2차원 배열입니다.  numpy에서는 행이 기본 단위입니다. 행렬은 행과 열이라는 인덱스를 가집니다.   
X=(xij)는 i번째 행, j번째 열에 있는 원소를 표현하는 것이라고 보면 됩니다. 전치행렬(Transpose matrix)은 행과 열의 인덱스가 바뀐 행렬입니다. 

* 백터를 만들어 보자

In [3]:
ar = np.array([1,2,3,4,5])
ar

array([1, 2, 3, 4, 5])

* 행렬을 만들어 보자

### 1차원

In [12]:
ar1 = np.array([1,2,3,4])
ar1

array([1, 2, 3, 4])

### 2차원

In [11]:
ar2 = np.array([[1,2,3,4,5],
              [6,7,8,9,10]
             ])
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### 3차원

In [14]:
ar3 = np.array([[1,2,3],
               [1,2,3],
               [1,2,3]])
ar3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# Numpy 기초

## * 배열

* 파이썬 리스트로 배열을 생성하는 방법

In [17]:
list1 =[1,2,3,4]
a = np.array(list1)
print(a)
a.shape

[1 2 3 4]


(4,)

In [18]:
b = np.array([[1,2,3],[1,2,3]])
print (b)
b.shape

[[1 2 3]
 [1 2 3]]


(2, 3)

## *특수한 배열의 생성

* zeros():배열에 모두 0을 집어넣음

In [19]:
aa = np.zeros((2,2))
aa

array([[0., 0.],
       [0., 0.]])

In [20]:
type(aa)

numpy.ndarray

* ones():배열에 모두 1을 집어 넣음

In [21]:
bb = np.ones((2,3))
bb

array([[1., 1., 1.],
       [1., 1., 1.]])

* full():배열에 사용자가 지정한 값을 넣음

In [22]:
cc = np.full((2,3),10)
cc

array([[10, 10, 10],
       [10, 10, 10]])

eye():대각선으로 1이고 나머지는 0인 2차원 배열을 생성

In [23]:
dd = np.eye(3)
dd

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

reshape():다차원으로 변형하는 함수

In [25]:
aa1=np.array(range(20)).reshape((5,4)) #range(n): 0~n-1까지의 숫자를 생성하는 함수
aa1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
aa2=np.array(range(o15)).reshape((3,5))
aa2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## * 배열 결합 

* concatenate 함수로 배열 합치기

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5])
arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5])

Numpy는 둘 이상의 배열을 특정 축(axis)을 따라서 합치는 concatenate메서드를 제공한다.  
배열들은 동일한 rank를 가져야하고, 합쳐질 축을 제외한 나머지 축으로 동일한 길이를 가져야 한다.  
만들어진 배열은 입력된 배열과 동일한 rank를 가지게 된다.

In [5]:
arr1 = np.array([[1,2],
                [3,4]])
arr2 = np.array([[5,6],
                 [7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
arr4 = np.concatenate((arr1, arr2), axis=1)
arr4

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

2차원 이상의 배열은 합칠 축을 지정할 수 있다.(디폴트,axis=0)
0은 세로축, 1은 가로축을 나타난다.

In [17]:
# 3개 아상도 가능하다
x = np.array([7,77,777])
print(np.concatenate([arr1, arr2, x]))

[  1   2   3   4   5   6   7  77 777]


* Stack 함수로 배열쌓기

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.stack((arr1, arr2), axis=0)
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr4 = np.stack((arr1, arr2), axis=1)
arr4

array([[1, 4],
       [2, 5],
       [3, 6]])

* stack함수는 배열들을 새로운 축으로 합치는 일을 한다.

In [19]:
np.vstack([arr1,arr2]) # 수직 스택

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
anp.hstack([arr1,arr2]) #1,2,3,4,5,6

array([1, 2, 3, 4, 5, 6])

## *배열의 차원 변환

* 배열의 차원을 변환 해주는 reshape

* reshape함수는 np.reshape(변경할 배열, 차원)또는 배열.reshape(차원)으로 사용 할 수 있으며, 현재의 배열의 차원을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

* 1차원과 2차원 변환

In [4]:
x = [1,2,3,4,5,6,7,8,9,10]
y = np.reshape(x,(2,5))
z = np.reshape(x,(5,2))
print(x)

print(z)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


## *데이터 타입

## *인덱싱/슬라이싱 

* 배열의 인덱싱  
일차원 배열의 인덱싱은 리스트의 인덱싱과 같다.

In [21]:
a = np.array([0,1,2,3,4])

In [22]:
a[2]

2

In [23]:
a[-1]

4

* 다차원 배열의 인덱싱은 콤마를 사용하여 접근할 수 있다.  
콤마(,)로 구분된 차원은 축(axis)라고 한다.

In [24]:
a = np.array([[0, 1, 2], [3, 4, 5]])

In [25]:
a[0, 0] #첫번쨰 행 첫번째 열 0

0

In [26]:
a[1, 2] #두번째 행 세번째 열 5

5

In [27]:
a[-1,-1] # 마지막행 마지막 열

5

* 배열 슬라이싱  
배열 객체로 구현한 다차원 배열의 원소 중 복수 개를 접근하려면 일반적인 파이썬 슬라이싱과 콤마(,)를 함께 사용하면 된다.

In [28]:
b = np.array([[0,1,2,3], [4,5,6,7]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
b[0, :] #첫번째 행 전체 

array([0, 1, 2, 3])

In [41]:
b[:, 2] #두번째 열 전체

array([2, 6])

In [38]:
b[1,0] #두번째 행 첫벌째 열

4

## *배열 조건 연산

## *마스킹

## *Broadcasting