# Numpy

Numpy란 무엇인가?

Numpy는 C언어로 구현된 파이썬 라이브러리로써, 고성능의 수치계산을 위해 제작되었습니다. Numerical Python의 줄임말이기도 한 Numpy는 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공합니다.

또한 이는 데이터분석을 할 때 사용되는 라이브러리인 pandas와 matplotlib의 기반으로 사용되기도 합니다

Numpy 설치법

conda install numpy 또는 pip install numpy

* Numpy를 가져오는 방법

In [1]:
import numpy as np # 넘파이를 쓸 때 관레적으로 np를 쓴다.

# 백터와 행렬

 * 백터는 숫자를 원소로 가지는 리스트(list) 또는 배열(array)입니다. np.array()는 행 백터로 나오게 됩니다.   백터는 공간에서 한 점을 나타냅니다. 1차원 공간에서는 백터는 수직선상에 놓인 숫자로 표현하게 됩니다. 2차원 공간에서의 백터는 x축과 y축으로 이뤄진 좌표평면의 한 점을 나타내는 것입니다. 백터는 원점으로부터 상대적 위치를 표현합니다.

* 벡터는 스칼라의 모임입니다

* 행렬은 벡터를 원소로 가지는 2차원 배열입니다.  numpy에서는 행이 기본 단위입니다. 행렬은 행과 열이라는 인덱스를 가집니다.   
X=(xij)는 i번째 행, j번째 열에 있는 원소를 표현하는 것이라고 보면 됩니다. 전치행렬(Transpose matrix)은 행과 열의 인덱스가 바뀐 행렬입니다. 

* 백터를 만들어 보자

In [3]:
ar = np.array([1,2,3,4,5])
ar

array([1, 2, 3, 4, 5])

* 행렬을 만들어 보자

### 1차원

In [12]:
ar1 = np.array([1,2,3,4])
ar1

array([1, 2, 3, 4])

### 2차원

In [11]:
ar2 = np.array([[1,2,3,4,5],
              [6,7,8,9,10]
             ])
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### 3차원

In [14]:
ar3 = np.array([[1,2,3],
               [1,2,3],
               [1,2,3]])
ar3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# Numpy 기초

## * 배열

* 파이썬 리스트로 배열을 생성하는 방법

In [17]:
list1 =[1,2,3,4]
a = np.array(list1)
print(a)
a.shape

[1 2 3 4]


(4,)

In [18]:
b = np.array([[1,2,3],[1,2,3]])
print (b)
b.shape

[[1 2 3]
 [1 2 3]]


(2, 3)

## *특수한 배열의 생성

* zeros():배열에 모두 0을 집어넣음

In [19]:
aa = np.zeros((2,2))
aa

array([[0., 0.],
       [0., 0.]])

In [20]:
type(aa)

numpy.ndarray

* ones():배열에 모두 1을 집어 넣음

In [21]:
bb = np.ones((2,3))
bb

array([[1., 1., 1.],
       [1., 1., 1.]])

* full():배열에 사용자가 지정한 값을 넣음

In [22]:
cc = np.full((2,3),10)
cc

array([[10, 10, 10],
       [10, 10, 10]])

eye():대각선으로 1이고 나머지는 0인 2차원 배열을 생성

In [23]:
dd = np.eye(3)
dd

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

reshape():다차원으로 변형하는 함수

In [25]:
aa1=np.array(range(20)).reshape((5,4)) #range(n): 0~n-1까지의 숫자를 생성하는 함수
aa1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
aa2=np.array(range(o15)).reshape((3,5))
aa2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## * 배열 결합 

## *배열의 차원 변환

## *데이터 타입

## *슬라이싱/인덱싱

## *배열 조건 연산

## *마스킹

## *Broadcasting