# pandas 기초

데이터 처리와 분석을 위한 라이브러리

In [1]:
import numpy as np
import pandas as pd

데이터 구조

## Series

* 1차원 구조로 되어 있는 데이터

pd.Series(data=None, index=None dtype=None, name=None, copy=None) 이런 구조로 되어있다. 데이터 인덱스 디타입 이름 설정 하고 싶으면 괄호안에 치고 넣으면되고 안 넣어도 None값으로 실행이 가능하다.


## Series 생성

pandas.Series(data,index,dtype,copy)

data - Series를 구성할 데이터 - ndarray,list,constants  
index - 필요한 정보를 잘 찾을 수 있게 일정한 순서로 정리된 배열  
dtype - 각 항목에 적용될 타입

In [7]:
ds = pd.Series()
ds

C:\Users\USER\AppData\Local\Temp\ipykernel_10012\334599869.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  ds = pd.Series()


Series([], dtype: float64)

ndarray의 데이터를 이용한 Series 생성

In [14]:
sampleData = np.array(['a','b','c','d'])
ex_series = pd.Series(sampleData)
ex_series

0    a
1    b
2    c
3    d
dtype: object

In [15]:
sampleData1 = np.array(['가','나','다','라','마'])
ex_series1 = pd.Series(sampleData1)
ex_series1

0    가
1    나
2    다
3    라
4    마
dtype: object

Dictionary를 이용한 Series 생성  
key 부분 index, 값 부분 values  
아래에서 key부분이 a 값 부분이 0 입니다.

In [19]:
sampleDict = {'a':0., 'b':1., 'c':2.}
ds = pd.Series(sampleDict)
ds

a    0.0
b    1.0
c    2.0
dtype: float64

In [20]:
sampleDict = {'a':0, 'b':1, 'c':2}
ds = pd.Series(sampleDict)
ds

a    0
b    1
c    2
dtype: int64

index/Position을 이용한 Series 접근

In [23]:
sample = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

In [28]:
sample[0] # 첫번째 값 접근

1

In [29]:
sample[1] #두번째 멤버까지 접근

2

In [30]:
sample[-2] 

4

In [33]:
s = pd.Series(data=np. random.randn(5), index=['a','b','c','d','e'])
s

a   -0.608374
b   -0.193200
c    0.017264
d    1.004149
e    0.139127
dtype: float64

슬라이싱/인덱스

Numpy와 같이 슬라이싱/인덱스와 같은 작업가능

In [34]:
s[0]

-0.6083743429815068

In [35]:
s[:3]

a   -0.608374
b   -0.193200
c    0.017264
dtype: float64

In [43]:
np.random.seed(42) # 난수는 42를 주로 사용하는데 별 이유는 없는 듯하다..
arr = np.random.randint(16,32,(4,4))
arr

array([[22, 19, 28, 30],
       [26, 23, 28, 20],
       [22, 25, 18, 22],
       [26, 26, 23, 20]])

In [46]:
arr[:3]

array([[22, 19, 28, 30],
       [26, 23, 28, 20],
       [22, 25, 18, 22]])

In [60]:
arr[:3,:3] #22,19,28


array([[22, 19, 28],
       [26, 23, 28],
       [22, 25, 18]])

In [62]:
arr[0:4,:2]

array([[22, 19],
       [26, 23],
       [22, 25],
       [26, 26]])

In [66]:
arr[3:,:4]

array([[26, 26, 23, 20]])

In [71]:
arr[0:4,3:4]

array([[30],
       [20],
       [22],
       [20]])

In [72]:
arr[0]

array([22, 19, 28, 30])

In [74]:
s[s>s.median()], s.median()

(d    1.004149
 e    0.139127
 dtype: float64,
 0.017263946003324614)